- src/lib.rs
Improve the error message when the file of the reference genome does not exist.
> get_lines: Improve error with non-existant file

- src/lib.rs
Set the `--outSAMmultNmax=10` parameter of STAR.
`test_ercc_align`: Test multimaps.
`parse_sam_to_records`: Fix bug affecting multimaps.
The default values are `--outFilterMultimapNmax=10 --outSAMmultNmax=-1`.
> Increase max multimaps from 1 to 10

- src/lib.rs
Set the `--outSAMmultNmax=-1` parameter of STAR.
A different read will be selected by STAR as the primary alignment when `--outSAMmultNmax=-1` vs `--outSAMmultNmax=999999999`. This behaviour is unexpected to me, but there you are.
See https://github.com/10XGenomics/STAR/blob/2c17c9ce6bf25f606c4f7a843b703e0692a9fcf6/source/ReadAlign_multMapSelect.cpp#L86
> DEFAULT_MULTN: Increase multimaps to unlimited

- Cargo.toml
- build.rs
- src/lib.rs
> fix memory leaks, add rerun-if

- star-sys/build.rs
~~Position independent code (PIC) is not needed for a static library, and non-PIC is more efficient than PIC.~~
Position independent code (PIC) is the default.
See https://docs.rs/cc/1.0.52/cc/struct.Build.html#method.pic
> star-sys/build.rs: Remove -fPIC and enable -Werror

- .travis.yml
- Cargo.lock
- Cargo.toml
Note: this PR only bumps htslib on the `no-mmap` branch, which we are currently using.
Bump travis rust version from 1.37 -> 1.47.
> bump htslib

- Cargo.toml
- star-sys/Cargo.toml
Some tools, like `cargo deny`, complain if a crate doesn't declare a license (even if the repo does).
> Add license declarations to Cargo.tomls.

- Cargo.toml
```
$ cargo diet
┌─────────────────────────────────────────────────┬─────────────┐
│ File                                            │ Size (Byte) │
├─────────────────────────────────────────────────┼─────────────┤
│ test/ercc92-1.2.0/star/sjdbList.out.tab         │           0 │
│ test/ercc92-1.2.0/star/sjdbList.fromGTF.out.tab │           0 │
│ test/ercc92-1.2.0/star/sjdbInfo.txt             │           6 │
│ .gitignore                                      │          20 │
│ test/ercc92-1.2.0/reference.json                │         365 │
│ test/ercc92-1.2.0/star/chrLength.txt            │         412 │
│ test/ercc92-1.2.0/star/chrStart.txt             │         557 │
│ test/ercc92-1.2.0/star/exonInfo.tab             │         783 │
│ test/ercc92-1.2.0/star/genomeParameters.txt     │ …
```
> Exclude test files from crate.

- .github/dependabot.yml
- .github/workflows/test.yml
- Cargo.lock
- deny.toml
- src/lib.rs
- star-sys/build.rs
- Enable cargo-deny and clippy in CI.
- Use packaged action to simplify caching in CI
- Run clippy fixes
- Update dependencies in Cargo.lock.
- Add dependabot config for github actions.
- Use `-fvisibility=hidden` when compiling STAR.  This prevents the symbols from being exported if orbit gets compiled into a `.so` for example, and just generally makes the linker's life easier.
> Modernizations and cleanups

- src/lib.rs
- star-sys/STAR/source/Genome.cpp
- star-sys/STAR/source/Genome.h
- star-sys/STAR/source/Genome_genomeGenerate.cpp
- star-sys/STAR/source/Parameters.cpp
- star-sys/STAR/source/Parameters.h
- star-sys/STAR/source/ReadAlign.cpp
- star-sys/STAR/source/ReadAlign.h
- star-sys/STAR/source/ReadAlign_chimericDetectionOldOutput.cpp
- star-sys/STAR/source/ReadAlign_createExtendWindowsWithAlign.cpp
- star-sys/STAR/source/ReadAlign_mapOneRead.cpp
- star-sys/STAR/source/ReadAlign_maxMappableLength2strands.cpp
- star-sys/STAR/source/ReadAlign_outputAlignments.cpp
- star-sys/STAR/source/ReadAlign_stitchPieces.cpp
- star-sys/STAR/source/SequenceFuns.cpp
- star-sys/STAR/source/SequenceFuns.h
- star-sys/STAR/source/Transcript.h
- star-sys/STAR/source/genomeSAindex.cpp
- star-sys/STAR/source/orbit.cpp
- star-sys/STAR/source/orbit.h
- star-sys/STAR/source/stitchAlignToTranscript.cpp
- star-sys/build.rs
- star-sys/src/lib.rs
Use unique_ptr to manage memory in ReadAlign and orbit front-end.  Try to do this in a minimally-invasive way so we don't have to touch too much other code.
Take a few things that shouldn't have been pointers and make them not be pointers.
Slab-allocate the storage for some arrays-of-arrays.
Make argv parameters const, for both the c++ side and the rust side. Clean up memory management for C strings on the rust side.
> Fix memory leaks in ReadAlign.

- star-sys/STAR/source/SequenceFuns.cpp
Fix `error: implicit instantiation of undefined template 'std::array<std::vector<unsigned long long>, 3>'` observed on macOS using `clang++`.
> star-sys: Include std::array

- star-sys/build.rs
As proposed in https://github.com/10XGenomics/orbit/pull/50, appears to build cleanly already.
> star-sys: Build with `_LIBCPP_REMOVE_TRANSITIVE_INCLUDES`

- .github/workflows/test.yml
Github has deprecated `ubuntu-18.04`, so move to a supported image version.
> gh-actions: Upgrade test workflow to `ubuntu-20.04`

- Cargo.toml
> Widen version range for rust-htslib

- star-sys/build.rs
Apple clang version 14.0.0 does not support `-mcmpxchg16b`.
It'd probably be better to check the precise version of `clang++` or check for compiler support some other way, but this fix works for now.
Fix the error:
```console
$ uname -a
Darwin fpx-l-amer01854 21.6.0 Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64 x86_64
$ clang++ --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
$ cargo check
…
CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
…
cargo:warning=clang: error: unknown argument: '-mcmpxchg16b'
…
error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" …
```
> Fix clang: error: unknown argument: '-mcmpxchg16b'

- star-sys/STAR/source/ReadAlign_maxMappableLength2strands.cpp
Variable-length arrays are not part of standard c++.
> chore: fix STAR warningns coming from clang 18

- src/lib.rs
- Use `try_fold` in `StarSettings::est_mem`
- Sort `use` statements
- Needed to bump `RUST_VERSION` from 1.65.0 to 1.79.0
Fix the clippy lint:
```
warning: usage of `Iterator::fold` on a type that implements `Try`
```
> style: Use try_fold in StarSettings::est_mem

- src/lib.rs
- star-sys/src/lib.rs
- `impl Send for InnerStarReference` to fix the clippy lint:
```
Error: error: usage of an `Arc` that is not `Send` and `Sync`
```
- Remove unused `impl Send for StarRef`
- Needed to bump `RUST_VERSION` from 1.65.0 to 1.79.0
Fix the clippy lint:
```
Error: error: usage of an `Arc` that is not `Send` and `Sync`
--> src/lib.rs:66:20
|
66 |             inner: Arc::new(inner),
|                    ^^^^^^^^^^^^^^^
|
= note: `Arc<InnerStarReference>` is not `Send` and `Sync` as `InnerStarReference` is not `Send`
= help: if the `Arc` will not used be across threads replace it with an `Rc`
= help: otherwise make `InnerStarReference` `Send` and `Sync` or consider a wrapper type such as `Mutex`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#arc_with_n …
```
> feat: impl Send for InnerStarReference for clippy

- .github/workflows/test.yml
- Cargo.lock
- Run `cargo update`
- Bump `RUST_VERSION` from 1.65.0 to 1.79.0
- Bump `CR_DENY_VERSION` from 0.13.5 to 0.14.23
- Ignore a `clippy::arc_with_non_send_sync` warning
See https://rust-lang.github.io/rust-clippy/master/index.html#/arc_with_non_send_sync
and https://github.com/rust-lang/rust-clippy/issues/11714
```console
❯ cargo clippy
Compiling star-sys v0.2.0 (/Users/shaun.jackman/work/deps/orbit/star-sys)
Checking orbit v0.2.1 (/Users/shaun.jackman/work/deps/orbit)
warning: usage of an `Arc` that is not `Send` and `Sync`
--> src/lib.rs:66:20
|
66 |             inner: Arc::new(inner),
|                    ^^^^^^^^^^^^^^^
|
= note: `Arc<InnerStarReference>` is not `Send` and `Sync` as `InnerStarReference` is not `Send`
= help: if the `Arc` will not used be across threads replace it with an …
```
> build(deps): Update Rust dependencies

- .github/workflows/test.yml
- deny.toml
- Bump `deny.toml` from version 1 to 2 and remove deprecated configuration fields
- Bump `cargo-deny` in GHA `.github/workflows/rust.yml` from version 0.14.23 to 0.16.1
> build(rs): Bump deny.toml to version 2

- src/lib.rs
For single bp reads, there is an ambiguity in the SAM format
```
read001	0	ref	1	255	1M	*	0	0	A	*
```
The read above could have a QV value of `*`, or no QV values at all.  Since htslib [sets a sentinel value of 255](https://github.com/samtools/htslib/blob/b14fffb4b5689696723634a20b85219be92f9d06/sam.c#L3029-L3030) in this case, it can lead to overflow in downstream operations.  Since we pass in a `qual` array for alignment, we can know it's not ambiguous and set the value back to it's correct value.
> fix: Edge Case Handling
